version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jacoballen-website
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      # Optionnel : pour le développement local
      # - ./:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web-network:
    driver: bridge
